// 공식 운영처·한국관광공사 자료로 확인한 2026 가을 추천.
// replacesSpotId가 있으면 기존 장소의 좌표와 지도 링크를 유지한 채 시즌 카피만 덮어쓴다.
// 서로 다른 장소 25곳에 재사용된 2025 단풍 지도는 장소별 근거가 아니므로 검수 보류한다.
const SEASONAL_AUDIT_HOLD_SOURCE = "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d";
const autumnWalkAdditions = [
  { id: "seocheon-sinseong-reeds", title: "신성리갈대밭", region: "충남", area: "서천군 한산면", address: "충남 서천군 한산면 신성리 125-1 일원", desc: "금강변 갈대밭 탐방로를 걷는 가을 산책 장소예요. 갈대 색과 풍성함은 날씨·시기에 따라 달라요.", sourceUrl: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=94908", admissionNote: "공식 관광 안내상 연중무휴·입장 무료. 일반 탐방 기준이며 프로그램 예약과는 별개예요. 기상·현장 통제와 갈대 상태는 방문 전 확인해 주세요." },
  { id: "siheung-okgu-park", title: "옥구공원", region: "경기", area: "시흥시 정왕동", desc: "억새동산과 산책로를 둘러보는 가을 나들이 장소예요. 현재 억새 절정 여부는 확인되지 않았어요.", sourceUrl: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188661", admissionNote: "공식 관광 안내상 24시간·연중무휴·무료인 공원이에요. 안내의 영문·국문 도로명 번호가 달라 장소명으로 지도를 검색해 주세요. 야간보다 밝은 시간 산책을 권해요." },
  { id: "daegu-daemyeong-wetland", title: "대명유수지", region: "대구", area: "달서구 대천동", address: "대구 달서구 대천동 816", desc: "갈대·억새 사이 생태탐방로와 데크를 걷는 가을 산책 장소예요. 현재 경관과 탐방로 통제 여부는 방문 전 확인해 주세요.", sourceUrl: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=190099", admissionNote: "공식 관광 안내상 연중무휴·무료, 09:00~18:00(동절기 17:00까지). 주차장은 없어요. 현장 운영 변경 가능성이 있으며 현재 개장 중이라는 의미는 아니에요." },
].map(spot => ({ ...spot, company: "both", emoji: "🌾", searchQuery: `${spot.region} ${spot.title}`, seasonLabel: "가을 산책 · 경관은 시기에 따라 달라요", seasonalTheme: "reeds", activeMonths: [9, 10, 11], sourceCheckedAt: "2026-10-06" }));
window.SEASONAL_SPOTS = [
  ...autumnWalkAdditions,
  {
    replacesSpotId: "incheon-sorae", title: "소래습지생태공원",
    desc: "풍차와 습지 탐방로를 따라 걷는 가을 산책 장소예요. 억새 경관은 시기에 따라 달라요.",
    seasonLabel: "가을 습지 산책 · 경관 확인 필요", activeMonths: [9, 10, 11],
    sourceUrl: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=80678", sourceCheckedAt: "2026-10-06",
  },
  {
    id: "goyang-autumn-flower-2026",
    title: "고양가을꽃축제",
    region: "경기",
    area: "고양시 일산동구",
    emoji: "🌼",
    desc: "일산호수공원에서 코스모스·백일홍 등 가을꽃을 따라 걷는 무료 나들이예요.",
    address: "경기 고양시 일산동구 노루목로 10, 일산호수공원 주제광장 일원",
    searchQuery: "고양가을꽃축제 일산호수공원 주제광장",
    company: "both",
    seasonLabel: "가을꽃 · 10월 11일까지",
    seasonalTheme: "autumn-flowers",
    availableFrom: "2026-10-01",
    availableUntil: "2026-10-11",
    sourceUrl: "https://www.mcst.go.kr/site/s_culture/festival/festivalView.jsp?pRo=79&pSeq=11802",
    sourceCheckedAt: "2026-10-06",
  },
  {
    replacesSpotId: "gyeongbok-night",
    title: "2026 경복궁 별빛야행",
    emoji: "🏯",
    desc: "해설과 궁중음식, 공연이 포함된 예약형 경복궁 야간 프로그램이에요.",
    address: "서울 종로구 사직로 161",
    seasonLabel: "2026 가을 · 10월 24일까지",
    availableFrom: "2026-09-02",
    availableUntil: "2026-10-24",
    sourceUrl: "https://www.kh.or.kr/cont/view/fest/month/menu/210?idx=110615&month=09&searchCategory1=600&searchCategory2=617&searchDate=202609&year=2026",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "seoul-forest",
    title: "서울숲 국제정원박람회",
    emoji: "🌿",
    desc: "10월 27일까지 167개 정원이 이어지는 도심 정원 산책. 서울숲에서 성수·한강변까지 천천히 걸어요.",
    seasonLabel: "2026 가을 · 10월 27일까지",
    availableFrom: "2026-09-01",
    availableUntil: "2026-10-27",
    sourceUrl: "https://www.seoul.go.kr/festa/garden/y2026/citizen-participation/faq?article=41527",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "hanul-park",
    title: "하늘공원 서울억새축제",
    emoji: "🌾",
    desc: "은빛 억새와 노을을 함께 보는 가을 산책. 10월 17~23일에는 야간 조명과 체험이 열려요.",
    seasonLabel: "2026 가을 · 축제 10월 17~23일",
    availableFrom: "2026-10-17",
    availableUntil: "2026-10-23",
    sourceUrl: "https://news.seoul.go.kr/env/archives/570795",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "gyeonggi-jaraseom",
    title: "자라섬 가을 꽃 페스타",
    emoji: "🌼",
    desc: "북한강 수변을 따라 형형색색 가을꽃을 걷는 코스. 주말에는 버스킹과 체험도 열려요.",
    seasonLabel: "2026 가을 · 10월 5일까지",
    availableFrom: "2026-09-12",
    availableUntil: "2026-10-05",
    sourceUrl: "https://korean.visitkorea.or.kr/kfes/detail/fstvlDetail.do?fstvlCntntsId=8b7f0ad9-384b-4b55-ba4b-5a6804cae161",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "gyeonggi-hwadamsup",
    title: "화담숲 가을 단풍",
    emoji: "🍁",
    desc: "단풍이 층층이 물드는 숲속 산책길. 가을에는 사전 예약 여부와 모노레일 잔여석을 먼저 확인해요.",
    seasonLabel: "가을 단풍 · 예약 확인",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=e77fe81a-7b0e-4a45-85fd-9231b46be194",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "daejeon-jangtaesan",
    title: "장태산 메타세쿼이아 단풍",
    emoji: "🌲",
    desc: "붉고 노랗게 물든 메타세쿼이아 숲을 스카이웨이에서 내려다보는 가을 산책 코스예요.",
    seasonLabel: "가을 단풍 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "jeonnam-suncheonman",
    title: "순천만습지 갈대 노을",
    emoji: "🌾",
    desc: "황금빛 갈대밭과 S자 수로가 함께 보이는 가을 명소. 해 질 무렵 용산전망대 풍경이 특히 좋아요.",
    address: "전남 순천시 순천만길 513-25",
    seasonLabel: "가을 갈대·노을",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=a34f5090-ba6d-4f7b-b359-9d7b1e810cd6",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "gyeongbuk-cheomseong",
    title: "첨성대 핑크뮬리 산책",
    emoji: "🩷",
    desc: "신라 유적과 분홍빛 핑크뮬리를 한 프레임에 담기 좋은 초가을 산책 코스예요.",
    seasonLabel: "가을 꽃 사진 명소",
    activeMonths: [9, 10],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=958955bd-83ae-4ef5-8f35-d2a8e0a5caea",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "seoul-nowon-moonlight-2026",
    title: "노원달빛산책",
    emoji: "🌙",
    region: "서울",
    area: "노원",
    desc: "당현천을 따라 빛 작품을 만나는 무료 야간 산책. 상계역에서 중계역 사이를 천천히 걸어요.",
    address: "서울 노원구 당현천 상계역~중계역 구간",
    searchQuery: "노원달빛산책 당현천",
    company: "both",
    moods: ["chill"],
    time: "night",
    seasonLabel: "2026 가을 · 10월 16일~11월 18일",
    availableFrom: "2026-10-16",
    availableUntil: "2026-11-18",
    sourceUrl: "https://festival.seoul.go.kr/festival/seasonal/list.do",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "seoul-changdeokgung-secret-garden",
    title: "창덕궁 후원 단풍",
    emoji: "🏯",
    region: "서울",
    area: "종로",
    desc: "고궁 연못과 정자 사이로 단풍이 겹쳐지는 가을 명소. 후원 관람은 예약 여부를 먼저 확인해요.",
    address: "서울 종로구 율곡로 99",
    searchQuery: "창덕궁 후원",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 단풍 · 예약 확인",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://royal.khs.go.kr/ROYAL/contents/R701000000.do",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "seoul-pureun-arboretum-autumn",
    title: "푸른수목원 단풍 산책",
    emoji: "🍂",
    region: "서울",
    area: "구로",
    desc: "철길 옆 수목원에서 단풍과 습지원 풍경을 함께 보는 조용한 도심 산책 코스예요.",
    address: "서울 구로구 연동로 240",
    searchQuery: "푸른수목원",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 단풍 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://parks.seoul.go.kr/maps/puleunsumogwon/puleunsumogwon_leaflet.pdf",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeonggi-pocheon-garden-festa-2026",
    title: "포천 한탄강 가든페스타",
    emoji: "🌸",
    region: "경기",
    area: "포천",
    desc: "한탄강 절경과 대규모 계절꽃 정원을 함께 보고 Y형 출렁다리까지 즐기는 가을 나들이예요.",
    address: "경기 포천시 관인면 창동로 832",
    searchQuery: "포천 한탄강 가든페스타",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "2026 가을 · 11월 1일까지",
    availableFrom: "2026-09-12",
    availableUntil: "2026-11-01",
    sourceUrl: "https://korean.visitkorea.or.kr/kfes/detail/fstvlDetail.do?fstvlCntntsId=5aa748cc-5523-4fca-bf80-3b331ba22212",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeonggi-gangcheon-island-autumn",
    title: "강천섬 은행나무길",
    emoji: "💛",
    region: "경기",
    area: "여주",
    desc: "남한강 섬을 노랗게 채우는 은행나무길과 넓은 잔디밭에서 피크닉하기 좋아요.",
    address: "경기 여주시 강천면 강천리길 88-60",
    searchQuery: "여주 강천섬 유원지",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 은행나무 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://access.visitkorea.or.kr/ms/detail.do?cotId=c62f1320-fb43-45b6-b6bf-b50a1db4714f",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gangwon-inje-autumn-flower-2026",
    title: "인제가을꽃축제",
    emoji: "🌼",
    region: "강원",
    area: "인제",
    desc: "국화·야생화 정원과 수변 산책로, 숲 체험을 함께 즐기는 무료 가을꽃 축제예요.",
    address: "강원 인제군 북면 용대리 1821-2",
    searchQuery: "인제가을꽃축제",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "2026 가을 · 10월 11일까지",
    availableFrom: "2026-09-24",
    availableUntil: "2026-10-11",
    sourceUrl: "https://korean.visitkorea.or.kr/kfes/detail/fstvlDetail.do?fstvlCntntsId=813eddb1-c961-4572-95b5-490dd8f54804",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gangwon-mindungsan-silver-grass",
    title: "민둥산 은빛 억새",
    emoji: "🌾",
    region: "강원",
    area: "정선",
    desc: "산등성이 전체가 은빛 억새로 출렁이는 트레킹 명소. 경사가 있어 편한 등산화를 준비해요.",
    address: "강원 정선군 남면 무릉리",
    searchQuery: "정선 민둥산 억새",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 억새 트레킹",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://www.yna.co.kr/view/AKR20260618058700062",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "chungnam-gokgyocheon-ginkgo",
    title: "곡교천 은행나무길",
    emoji: "💛",
    region: "충남",
    area: "아산",
    desc: "곡교천을 따라 은행나무 수백 그루가 노랗게 이어지는 평탄한 산책·자전거 코스예요.",
    address: "충남 아산시 염치읍 송곡리",
    searchQuery: "아산 곡교천 은행나무길",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 은행나무 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=fae63e1d-5b79-4bd6-b82c-2e35903f4192",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeonbuk-naejangsan-autumn",
    title: "내장산 단풍터널",
    emoji: "🍁",
    region: "전북",
    area: "정읍",
    desc: "붉은 단풍터널과 내장사까지 이어지는 대표 가을길. 절정기에는 대중교통과 이른 방문이 편해요.",
    address: "전북 정읍시 내장산로 1207",
    searchQuery: "내장산 국립공원 내장사",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 단풍 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeju-saebyeol-oreum-autumn",
    title: "새별오름 억새 능선",
    emoji: "🌾",
    region: "제주",
    area: "애월",
    desc: "완만한 오름 능선과 억새가 함께 빛나는 가을 제주 명소. 바람이 강해 겉옷을 챙겨요.",
    address: "제주 제주시 애월읍 봉성리 산 59-8",
    searchQuery: "제주 새별오름",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 억새 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://www.visitjeju.net/kr/detail/view?contentsid=CONT_000000000500309&menuId=DOM_000001718000000000",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "sokcho-gwongeumseong",
    title: "설악산 권금성 단풍",
    emoji: "🚠",
    desc: "케이블카로 올라 울산바위와 외설악의 단풍 파노라마를 보는 코스. 성수기에는 대기 시간을 넉넉히 잡아요.",
    seasonLabel: "가을 산악 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "chuncheon-namiseom",
    title: "남이섬 은행나무길",
    emoji: "💛",
    desc: "강 위의 섬을 노랗게 물들이는 은행나무길과 메타세쿼이아길을 함께 걷는 가을 나들이예요.",
    seasonLabel: "가을 은행나무·단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "jeonnam-meta",
    title: "담양 메타세쿼이아 단풍길",
    emoji: "🌲",
    desc: "곧게 뻗은 메타세쿼이아가 황금빛으로 변하는 길. 관방제림과 죽녹원까지 묶기 좋아요.",
    address: "전남 담양군 담양읍 메타세쿼이아로 12",
    seasonLabel: "가을 숲길 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "gwangju-mudeung",
    title: "무등산 가을 단풍",
    emoji: "⛰️",
    desc: "증심사 숲길부터 서석대까지 난이도에 맞춰 걷는 광주의 대표 단풍 산행지예요.",
    address: "광주 북구 금곡동 산 1-1",
    seasonLabel: "가을 단풍 트레킹",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "gyeongbuk-hahoe",
    title: "안동 하회마을 가을 산책",
    emoji: "🏘️",
    desc: "초가와 기와지붕 너머 황금 들판이 펼쳐지는 가을 풍경. 부용대 전망까지 함께 둘러봐요.",
    seasonLabel: "가을 고택·들녘",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    replacesSpotId: "ulsan-taehwagang",
    title: "태화강 국가정원 가을 산책",
    emoji: "🌾",
    desc: "십리대숲과 억새 군락, 계절꽃 정원을 한 번에 걷는 평탄한 강변 산책 코스예요.",
    seasonLabel: "가을 억새·정원",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "incheon-grand-park-autumn",
    title: "인천대공원 단풍터널",
    emoji: "🍁",
    region: "인천",
    area: "남동",
    desc: "호수와 수목원 사이로 긴 단풍터널이 이어지는 수도권 대표 가을 산책 명소예요.",
    address: "인천 남동구 무네미로 236",
    searchQuery: "인천대공원",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 단풍 추천",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gangwon-woljeongsa-autumn",
    title: "월정사 전나무숲 단풍",
    emoji: "🌲",
    region: "강원",
    area: "평창",
    desc: "오대산 전나무숲길의 깊은 초록과 붉은 단풍을 함께 보는 고요한 사찰 산책이에요.",
    address: "강원 평창군 진부면 오대산로 374-8",
    searchQuery: "오대산 월정사 전나무숲길",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 숲길·단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "chungbuk-cheongnamdae-autumn",
    title: "청남대 단풍 산책",
    emoji: "🍂",
    region: "충북",
    area: "청주",
    desc: "대청호를 끼고 대통령길과 메타세쿼이아 숲을 걷는 호젓한 가을 산책 코스예요.",
    address: "충북 청주시 상당구 문의면 청남대길 646",
    searchQuery: "청남대",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 단풍·호수",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "chungbuk-songnisan-sejo-trail",
    title: "속리산 세조길 단풍",
    emoji: "🥾",
    region: "충북",
    area: "보은",
    desc: "법주사에서 저수지와 계곡을 따라 걷는 완만한 숲길. 산행 부담 없이 단풍을 즐겨요.",
    address: "충북 보은군 속리산면 법주사로 84",
    searchQuery: "속리산 세조길",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 단풍 걷기",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "chungnam-oseosan-silver-grass",
    title: "오서산 억새 능선",
    emoji: "🌾",
    region: "충남",
    area: "보령",
    desc: "서해를 내려다보는 능선에 억새가 출렁이는 충남 대표 가을 산행지예요.",
    address: "충남 보령시 청소면 성연리",
    searchQuery: "보령 오서산 억새",
    company: "both",
    moods: ["active"],
    time: "day",
    seasonLabel: "가을 억새 산행",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "chungnam-onbit-autumn",
    title: "온빛자연휴양림 단풍",
    emoji: "🏡",
    region: "충남",
    area: "논산",
    desc: "메타세쿼이아 숲과 호숫가 목조 건물이 이국적인 풍경을 만드는 가을 사진 명소예요.",
    address: "충남 논산시 벌곡면 황룡재로 480-113",
    searchQuery: "논산 온빛자연휴양림",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 숲 사진 명소",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "sejong-gobok-reservoir-autumn",
    title: "고복저수지 수변 단풍길",
    emoji: "🌊",
    region: "세종",
    area: "연서",
    desc: "물가를 따라 데크길과 단풍이 이어지는 조용한 드라이브·산책 코스예요.",
    address: "세종 연서면 용암리",
    searchQuery: "세종 고복저수지",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 수변 산책",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeonbuk-seonunsa-autumn",
    title: "선운사 도솔천 단풍",
    emoji: "🍁",
    region: "전북",
    area: "고창",
    desc: "도솔천 물빛에 붉은 단풍과 고찰 풍경이 비치는 전북 대표 가을 명소예요.",
    address: "전북 고창군 아산면 선운사로 250",
    searchQuery: "고창 선운사",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 단풍·고찰",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeonbuk-maisan-autumn",
    title: "마이산 탑사 단풍",
    emoji: "🪨",
    region: "전북",
    area: "진안",
    desc: "말귀 모양 두 봉우리와 신비로운 돌탑, 단풍이 한 장면에 들어오는 독특한 가을 여행지예요.",
    address: "전북 진안군 마령면 마이산남로 130",
    searchQuery: "진안 마이산 탑사",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 단풍·기암",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeonnam-baegyangsa-autumn",
    title: "백양사 아기단풍",
    emoji: "🍁",
    region: "전남",
    area: "장성",
    desc: "쌍계루 연못과 작고 선명한 아기단풍이 어우러지는 남도 대표 늦가을 풍경이에요.",
    address: "전남 장성군 북하면 백양로 1239",
    searchQuery: "장성 백양사",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "늦가을 아기단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeonnam-piagol-autumn",
    title: "지리산 피아골 단풍",
    emoji: "🏞️",
    region: "전남",
    area: "구례",
    desc: "연곡사에서 계곡을 따라 붉은 단풍이 깊어지는 지리산 대표 가을 트레킹 코스예요.",
    address: "전남 구례군 토지면 내동리",
    searchQuery: "지리산 피아골계곡",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 계곡 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=44bfd797-1e6a-4b75-99e0-b06e47441e68",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeongbuk-bulguksa-autumn",
    title: "불국사 단풍",
    emoji: "🏯",
    region: "경북",
    area: "경주",
    desc: "천년 사찰의 돌계단과 다보탑 주변을 붉게 채우는 단풍을 함께 보는 고전적인 가을 코스예요.",
    address: "경북 경주시 불국로 385",
    searchQuery: "경주 불국사",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 단풍·문화유산",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeongbuk-mungyeongsaejae-autumn",
    title: "문경새재 단풍길",
    emoji: "🥾",
    region: "경북",
    area: "문경",
    desc: "옛 과거길과 계곡, 세 개의 관문을 따라 오색 단풍 속을 오래 걷기 좋은 길이에요.",
    address: "경북 문경시 문경읍 새재로 932",
    searchQuery: "문경새재 도립공원",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 옛길 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeongnam-tongdosa-autumn",
    title: "통도사 무풍한송길 단풍",
    emoji: "🌲",
    region: "경남",
    area: "양산",
    desc: "소나무가 굽이치는 무풍한송길과 영축산 단풍을 함께 만나는 고즈넉한 사찰 산책이에요.",
    address: "경남 양산시 하북면 통도사로 108",
    searchQuery: "양산 통도사",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 숲길·고찰",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeongnam-hwangmaesan-silver-grass",
    title: "황매산 억새평원",
    emoji: "🌾",
    region: "경남",
    area: "합천",
    desc: "넓은 고원 전체가 은빛 억새로 출렁이고 능선 너머 일몰까지 보기 좋은 가을 산행지예요.",
    address: "경남 합천군 가회면 황매산공원길 331",
    searchQuery: "합천 황매산 억새",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "가을 억새 트레킹",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "gyeongnam-jinju-lantern-2026",
    title: "진주남강유등축제",
    emoji: "🏮",
    region: "경남",
    area: "진주",
    desc: "남강과 진주성을 수상등·육상등·드론 쇼가 밝히는 대표 가을 야간 축제예요.",
    address: "경남 진주시 남강로 626",
    searchQuery: "진주남강유등축제",
    company: "both",
    moods: ["chill", "active"],
    time: "night",
    seasonLabel: "2026 가을 · 10월 3~18일",
    availableFrom: "2026-10-03",
    availableUntil: "2026-10-18",
    sourceUrl: "https://korean.visitkorea.or.kr/kfes/detail/fstvlDetail.do?fstvlCntntsId=aebdd924-73cd-4187-be5e-ba29ccf19c49",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "busan-hwamyeong-arboretum-autumn",
    title: "화명수목원 단풍",
    emoji: "🌳",
    region: "부산",
    area: "북구",
    desc: "금정산 자락의 부산 첫 공립수목원에서 숲과 계곡, 단풍을 함께 즐기는 코스예요.",
    address: "부산 북구 산성로 299",
    searchQuery: "부산 화명수목원",
    company: "both",
    moods: ["chill", "active"],
    time: "day",
    seasonLabel: "가을 수목원 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "daegu-arboretum-autumn",
    title: "대구수목원 단풍",
    emoji: "🍂",
    region: "대구",
    area: "달서",
    desc: "다양한 단풍 수종과 산책로가 잘 갖춰져 늦가을까지 가볍게 걷기 좋은 도심 수목원이에요.",
    address: "대구 달서구 화암로 342",
    searchQuery: "대구수목원",
    company: "both",
    moods: ["chill"],
    time: "day",
    seasonLabel: "가을 수목원 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeju-cheona-valley-autumn",
    title: "한라산 천아계곡 단풍",
    emoji: "🏞️",
    region: "제주",
    area: "제주",
    desc: "한라산 둘레길 숲과 계곡이 붉고 노랗게 물드는 제주 대표 단풍 트레킹 코스예요.",
    address: "제주 제주시 애월읍 봉성리",
    searchQuery: "한라산 둘레길 천아계곡",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "제주 가을 단풍",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=10b01f3d-cbb4-46c6-904a-f5979114440d",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "jeju-ttarabi-oreum-autumn",
    title: "따라비오름 억새",
    emoji: "🌾",
    region: "제주",
    area: "표선",
    desc: "부드러운 능선과 분화구를 따라 억새 물결이 이어지는 제주 동쪽의 가을 오름이에요.",
    address: "제주 서귀포시 표선면 가시리 산 62",
    searchQuery: "제주 따라비오름",
    company: "both",
    moods: ["active", "chill"],
    time: "day",
    seasonLabel: "제주 가을 억새",
    activeMonths: [9, 10, 11],
    sourceUrl: "https://www.visitjeju.net/kr/detail/view?contentsid=CONT_000000000500270",
    sourceCheckedAt: "2026-09-27",
  },
].map((spot) => spot.sourceUrl === SEASONAL_AUDIT_HOLD_SOURCE ? {
  ...spot,
  auditStatus: "hold",
  auditNote: "2025 전국 단풍 지도는 이 장소의 주소·현재 운영 여부를 직접 입증하지 않아 장소별 출처 확인 전 노출 보류",
} : spot);

// 원본 카탈로그에는 남아 있어도 추천·검색에서는 제외한다.
// 경복궁 별빛야행은 위의 활성 시즌 레코드가 있을 때만 예외적으로 노출된다.
// Only researched additions with explicit admission evidence are promoted.
window.SEASONAL_ADMISSION_AUDIT = [...autumnWalkAdditions.map(spot => ({
  id: spot.id, activities: ["walk"], reviewStatus: "conditional",
  reason: "공식 관광 안내로 일반 무료 산책과 가을 경관의 장소 근거 확인. 현재 경관·당일 통제 및 예약 불필요 직접 문구는 미확인.",
  sourceUrl: spot.sourceUrl, sourceCheckedAt: spot.sourceCheckedAt, admissionNote: spot.admissionNote,
})), {
  id: "goyang-autumn-flower-2026",
  activities: ["walk"],
  reviewStatus: "verified",
  reason: "문체부 2026 행사 안내가 가을꽃 관람·무료 자유 방문과 행사 기간을 명시해 산책으로 분류.",
  sourceUrl: "https://www.mcst.go.kr/site/s_culture/festival/festivalView.jsp?pRo=79&pSeq=11802",
  sourceCheckedAt: "2026-10-06",
  admissionNote: "10월 1~11일 09:00~18:00 무료 자유 방문. 별도 체험 조건과 기상에 따른 운영 변경은 방문 전 확인해 주세요. 현재 시각의 개장 여부·꽃 절정은 보장하지 않아요.",
  availableFrom: "2026-10-01",
  availableUntil: "2026-10-11",
}];
window.CATALOG_EXCLUSIONS = [
  {
    id: "gyeongbok-night",
    reason: "seasonal_event_only",
    availableUntil: "2026-10-24",
    sourceUrl: "https://www.kh.or.kr/cont/view/fest/month/menu/210?idx=110615&month=09&searchCategory1=600&searchCategory2=617&searchDate=202609&year=2026",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "hangang-pool",
    reason: "ended",
    availableUntil: "2026-08-30",
    sourceUrl: "https://hangang.seoul.go.kr/www/eventMng/detail.do?evntSn=432&mid=538&srchType=list",
    sourceCheckedAt: "2026-09-27",
  },
  {
    id: "yeouido-nightmarket",
    reason: "current_schedule_unverified",
    sourceUrl: "https://hangang.seoul.go.kr/www/bbsPost/17/644/detail.do?mid=604",
    sourceCheckedAt: "2026-09-27",
  },
];
